server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_franchise
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
